# User config
author: "VANNEY LIGHTING"
tagline: ""
description: "We have been focusing on lighting solutions over a decade. Well-crafted products are provided to customers all around the world."
keywords: "lighting"
email: "justin@vaneey.com | kenlisten@vaneey.com"
phone: "0086-(0)760-87683570"
address: "14 Qingfeng Road, Henglan, Zhongshan, Guangdong 528400, China"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
